compressionLevel: mixed

enableGlobalCache: true

nmMode: hardlinks-local

nodeLinker: node-modules

npmPublishAccess: public

# 发布到 npmjs.org；本地先 npm login，CI 使用 GitHub Secret NPM_TOKEN
npmPublishRegistry: 'https://registry.npmjs.org'

yarnPath: .yarn/releases/yarn-4.5.3.cjs
